### ISSUE TITLE
Filesafe doesn't install

### ISSUE THREAD

**Issue by JPL1** [standardnotes/filesafe-js#5]
`Error installing locally: error-downloading https://github.com/standardnotes/filesafe-client/archive/2.0.10.zip 
`
Is the filename wrong? - that link points to filesafe-bar-2.0.10.zip

I tried downloading that in appdata/roaming/standardnotes/extensions/downloads but is still doesn't work - ie I tried to import it (said it had succeeded) but I still get the same error message and am unable to activate it

Windows 10

**Comment by atmoio** [comment]
When I enter that URL in my browser it triggers a download. Are you using our official extensions or self-hosted?

**Comment by JPL1** [comment]
No problem - just logged out and in again. Working now. I think it's because my subscription has just renewed
